apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        prova: pep
        josep: mariaoiiieee
    spec:
      initContainers:
      - name: init-create-dir
        image: alpine
        command: ['sh', '-c', 'sleep 5 && echo "creating dir"']
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-uii
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-uii
  template:
    metadata:
      labels:
        app: guestbook-uii
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-uii
        ports:
        - containerPort: 80
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookservice
  labels:
    app: webhookservice
spec:
  selector:
    matchLabels:
      app: webhookservice
  template:
    metadata:
      labels:
        app: webhookservice
    spec:
      containers:
        - name: micro
          image: marc/webhook-demo:1.6.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            periodSeconds: 14
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            periodSeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 512Mi
---
